### ISSUE TITLE
where is the exe ?

### ISSUE THREAD

**Issue by makethpanda** [icholy/redigram#10]
hi, i am having trouble understanding how the bot works, i do not want to waste your time nor anger anyone with this, i didnt make the bot fully work yet but i am capable of putting in the commands in cmd and everything seems to work (exept for the font but thats something else) i see people in previous issues talking about a .exe file, while i do not see or know of, where is it ? how do you access it ? and am i doing something wrong ?

**Comment by icholy** [comment]
You need to learn how to use the command line (cmd).

**Comment by makethpanda** [comment]
That's the thing, I do (or think I do) but could you just explain quickly what I'm doing wrong (or how dumb I am) if it isn't too much of a bother ?
Thanks

**Comment by makethpanda** [comment]
and what are the cmd commands needed to use the bot now ?

**Comment by makethpanda** [comment]
nvm fixed it
