### ISSUE TITLE
main.go:65:13: undefined: Submission

### ISSUE THREAD

**Issue by lookingforhelp** [icholy/redigram#6]
im stuck with this error
main.go:65:13: undefined: Submission
i need help from anyone who solved it.

**Comment by icholy** [comment]
How am I supposed to help you if you didn't tell me what you did?

**Comment by lookingforhelp** [comment]
when i tried running the program this is the error message im getting i only changed the username password and subreddit

**Comment by icholy** [comment]
how the fuck did you "try running the program"?

**Comment by lookingforhelp** [comment]
using the console on linux i typed 
go run main.go

**Comment by icholy** [comment]
Use `go build` to compile it and then run the binary.

``` sh
$ go build
$ ./redigram --help
```

**Comment by lookingforhelp** [comment]
using go build did nothing still getting the same error message
type Post struct {
	Image      image.Image
	Caption    string
	Submission Submission
}
the problem is in the Submission line yet i cant seem to understand what the problem is

**Comment by icholy** [comment]
There is no problem, https://imgur.com/Ga7R3Kv

**Comment by icholy** [comment]
Your brain does literally nothing. Stop wasting my time.

**Comment by lookingforhelp** [comment]
damn :(

**Comment by makethpanda** [comment]
@DeathNoteOnline after what you did you USE the options -password abcd -username qwerty ect...

**Comment by icholy** [comment]
@makethpanda don't hijack unrelated issues.
