### ISSUE TITLE
I am getting this error and I have no idea how to solve it

### ISSUE THREAD

**Issue by L0kiCZ** [icholy/redigram#8]
2018/12/03 09:10:52 failed to login: json: cannot unmarshal string into Go struct field Nametag.gradient of type int64

**Comment by icholy** [comment]
@L0kiCZ did you resolve this?

**Comment by icholy** [comment]
Looks like we need to the goinsta dependency

https://github.com/ahmdrz/goinsta/issues/176

**Comment by L0kiCZ** [comment]
@icholy well, i could not resolve it on first account, but on the other one, it works just fine. So I am going to close my account, wait couple days and try again as wc311 said in issue number 3.

**Comment by L0kiCZ** [comment]
@icholy It is up and running, all i had to do is to change Gradient from int64 to string in types.go. Thanks a lot.

**Comment by icholy** [comment]
@L0kiCZ I've updated the dependency which should fix this.
